# Generated by Django 5.2.7 on 2025-10-09 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Province')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Is Valid')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'db_table': 'provinces',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='Device UUID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Login')),
                ('device_type', models.PositiveSmallIntegerField(choices=[(1, 'Web'), (2, 'IOS'), (3, 'Android')], default=3, verbose_name='Device Type')),
                ('device_os', models.CharField(blank=True, max_length=30, null=True, verbose_name='Device OS')),
                ('app_version', models.CharField(blank=True, max_length=30, null=True, verbose_name='App Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nickname')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, max_length=30, null=True, verbose_name='Gender')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.province')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
    ]
